### ISSUE TITLE
Unmanaged->Manged delegates are wrong

### ISSUE THREAD

**Issue by TechnikEmpire** [TechnikEmpire/HttpFilteringEngine#69]
The delegates defined in the managed `ref class Engine` for providing C style callbacks to the unmanaged "side" are wrong. They need to be declared as unmanaged callbacks with the calling convention explicitly set to cdecl.

`[UnmanagedFunctionPointer(CallingConvention::Cdecl)]`

Without this modification, the calling convention defaults to stdcall and this explodes the universe.

**Comment by PhyxionNL** [comment]
> this explodes the universe.

At least it's fixed now :+1:

**Comment by TechnikEmpire** [comment]
lol, yeah. Looks like everything is fixed now with this, except for the improvements that I've filed. Build instructions on the Wiki are being created (ported from a previous, unpublished generation of this project) and will be done in the next couple of days as a published binary release candidate of [Stahp It](https://github.com/TechnikEmpire/StahpIt-WPF) is impending.

**Comment by PhyxionNL** [comment]
Nice work on everything :+1:

**Comment by TechnikEmpire** [comment]
@Phyxion thx
