### ISSUE TITLE
Is there a sample program

### ISSUE THREAD

**Issue by sunflover** [TechnikEmpire/HttpFilteringEngine#72]
If there is an example program (such as advertising filtering) is better.

I am still a newbie in the network, I know that this is what I want, but I can not use.

**Comment by TechnikEmpire** [comment]
There currently isn't a sample program built into this repository. This library was designed exclusively for use in my other program called [Stahp It](https://github.com/TechnikEmpire/StahpIt-WPF). As I say on the ReadME, this project needs a bit of an overhaul. It started out as both a proxy and a content filter based on the proxy, but got merged into a single library.
