### ISSUE TITLE
VS solution for native build.

### ISSUE THREAD

**Issue by kirillv** [TechnikEmpire/HttpFilteringEngine#74]
Currently there is only .net assembly project. It would be great if there would be native dll or static library project.
Thanks in advance!

**Comment by TechnikEmpire** [comment]
Yep, it's actually pretty easy to change this. If you simply remove the "HttpFilteringEngineManaged.cpp" and "HttpFilteringEngineManaged.hpp" files, you'll get a proper native DLL with a C interface. The .net assembly / CLR support is actually a per-file settings, not a project or configuration wide setting. I'll add new targets when I get the chance, thanks for raising this issue.

**Comment by kirillv** [comment]
And one more question - is it possible to build with VS2013?

**Comment by TechnikEmpire** [comment]
Doubt it, given that there are some C++11 things that are not supported in VS2013 used here. The solution is a VS2015 solution.

**Comment by TechnikEmpire** [comment]
@kirillv This will be addressed shortly. I'm going to drop the managed interface from the project and leave it up to Pinvoke to use in .NET.

**Comment by kirillv** [comment]
@TechnikEmpire Thanks in advance! Ive done it by myself but it would be cool to have this out of box.

**Comment by TechnikEmpire** [comment]
Closing this, as this will be resolved in https://github.com/TechnikEmpire/HttpFilteringEngine/issues/76.
