### ISSUE TITLE
解析EasyList China+EasyList 规则的时候会出错

### ISSUE THREAD

**Issue by whitezhan** [TechnikEmpire/HttpFilteringEngine#77]
比如这条规则 ： 2muslim.com###frameD3x9G6_center > :nth-child(2n)
GQ项目里面的HttpFilteringEngine\deps\gq\src\Parser.cpp的892行  rhs =std::stoi(rhss);
这时候rhss的值为空字符串

**Comment by TechnikEmpire** [comment]
From what Google translate is giving me, looks like you're reporting a bug with GQ, parsing nth child strings? Can you open a bug ticket here: https://github.com/TechnikEmpire/GQ ? I'll open one later today if you don't. Thanks for reporting.

**Comment by TechnikEmpire** [comment]
@whitezhan I've migrated this issue to GQ's repo. You can find it here:

https://github.com/TechnikEmpire/GQ/issues/10
