### ISSUE TITLE
Proxy certificate

### ISSUE THREAD

**Issue by kirillv** [TechnikEmpire/HttpFilteringEngine#82]
It would be greate if proxy would install generated cert like fiddler if none is provided.

**Comment by TechnikEmpire** [comment]
@kirillv The engine does this. You can see the code here:

https://github.com/TechnikEmpire/HttpFilteringEngine/blob/master/src/te/httpengine/mitm/secure/WindowsInMemoryCertificateStore.cpp#L91

Or are we talking about something else?

**Comment by kirillv** [comment]
@TechnikEmpire sorry, you are right. missed it!
